[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.build]
cmds = [
  "pip install -r backend/requirements.txt",
  "cd frontend && npm install && npm run build"
]

[phases.start]
cmd = "python backend/app/main.py"
