providers = ["python", "node"]

[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.build]
cmds = [
  "cd backend",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt",
  "python -m pip list",
  "cd ../frontend",
  "npm install",
  "npm run build"
]

[phases.start]
cmd = "python -m backend.app.main"
