providers = ["python", "node"]

[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.build]
cmds = [
  "cd backend && pip install -r requirements.txt",
  "cd ../frontend && npm install && npm run build"
]

[start]
cmd = "python -m backend.app.main"
