[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.build]
cmds = [
  "cd backend && pip install -r requirements.txt && pip list",
  "cd ../frontend && npm install && npm run build"
]

[phases.start]
cmd = "python -m backend.app.main"
