# nixpacks.toml
providers = ["python"]     # quitas "node" para que no genere perfil nodejs

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "npm install --prefix frontend"     # npm viene preinstalado en el builder python
]

[phases.build]
cmds = [
  "npm run --prefix frontend build"
]

[start]
cmd = "python backend/app/main.py"
