name: Deploy to Railway

on:
  push:
    branches:
      - main  # o el nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias de frontend
        working-directory: frontend
        run: npm install

      - name: Compilar el frontend
        working-directory: frontend
        run: npm run build

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Instalar dependencias de Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Confirmar archivos generados
        run: ls -la frontend/dist

      # Esta línea es opcional, Railway puede manejar el deploy desde GitHub automáticamente.
