name: Deploy and Test

on:
  push:
    branches:
      - main # o la rama que uses para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Deploy en Railway
        uses: railwayapp/railway-action@v1
        with:
          railwayToken: cde21252-834a-4438-82f8-974e3f6053e5
          projectId: c6a3ee06-4d8e-43d5-90ec-3b7a64dcb646

      - name: Esperar unos segundos para que el deploy termine
        run: sleep 20

      - name: Verificar que la página responde (HTTP 200)
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://tuapp.railway.app | grep 200
